config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'about' => 'pages#about'

  get 'drone' => 'pages#drone'

  get 'survey' => 'pages#survey'

  get 'print' => 'pages#print'

  get 'portfolio' => 'pages#portfolio'

  get 'contacts' => 'pages#contacts'

  get 'privacy' => 'pages#privacy'

  get 'archeologia' => 'pages#archeologia'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def drone
  end

  def survey
  end

  def archeologia
  end

  def print
  end

  def portfolio
  end

  def contacts
  end
  
  def privacy
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="container-fluid">
	<div class="container">
		<div class="row-top contacts s1">
			<div class="col-sm-4 center-text">
				<p class="b">VERTICAL EYE<br>Drone solutions
				<br>via Mazzini, 156<br>41049 Sassuolo (MO)</p>
			</div>
			<div class="col-sm-4 phone" id="phone">
				<p class="b center-text">TELEFONO</p>				
				<ul class="ul-lefted">
					<li><a href="tel:+39 3400549443" class="row"><i class="material-icons">smartphone</i>+39 3400549443 - Andrea</a></li>
					<li><a href="tel:+39 3466388256" class="row"><i class="material-icons">smartphone</i>+39 3466388256 - Filippo</a></li>
				</ul>
			</div>
			<div class="col-sm-4 center-text mail" id="mail">
				<p class="b">MAIL</p>
				<ul class="ul-lefted">
					<li><a href="mailto:verticaleye18@gmail.com" class="row"><i class="material-icons">mail</i>verticaleye18@gmail.com</a></li>
				</ul>
			</div>
		</div>
		<br>
		<div class="row social" id="">
			<div class="col-4 center-text">
			</div>
			<div class="col-4 center-text row">
				<div class="social-container facebook" id="">
					<%= link_to image_tag("facebook.png", alt: "facebook"), 'https://www.facebook.com/verticaleye18/' %>
	      </div>
	      <div class="social-container instagram" id="">
					<%= link_to image_tag("insta.png", alt: "instagram"), 'https://www.instagram.com/vertical_eye/?hl=it' %>
	      </div>
			</div>
			<div class="col-4 center-text">
			</div>
		</div>
		<div class="row s0" id="lower">
			<div class="col-4 center-text">
				<p>Vertical Eye - Drone Solutions ©2020</p>
			</div>
			<div class="col-4 center-text">
				<a href="https://www.iubenda.com/privacy-policy/47765479" class="iubenda-nostyle iubenda-embed" title="Privacy Policy ">Privacy Policy</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src="https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script>
			</div>
			<div class="col-4 center-text">
				<a href="https://www.iubenda.com/privacy-policy/47765479/cookie-policy" class="iubenda-nostyle iubenda-embed" title="Cookie Policy ">Cookie Policy</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src="https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script>
			</div>
		</div>		
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="container-fluid" id="header">
	<div class="container-sm row">
		<div class="logo-container col" id="head-logo">
			<%= link_to image_tag("logo-tricolore.png", alt: "Verticaleye_logo"),
	            root_path %>
		</div>
		<div class="col" id="navbar">
			<nav id="pc-nav">
				<ul class="nav-list ul-lefted">
					<li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
					<li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
					<li class="<%= 'active' if current_page?(drone_path) %>"><%= link_to "Drone", drone_path %></li>
					<li class="<%= 'active' if current_page?(survey_path) %>"><%= link_to "Rilievi", survey_path %></li>
					<li class="<%= 'active' if current_page?(archeologia_path) %> invisible"><%= link_to "Archeologia", archeologia_path %></li>
					<li class="<%= 'active' if current_page?(print_path) %>"><%= link_to "Stampa 3D", print_path %></li>	
					<li class="<%= 'active' if current_page?(portfolio_path) %>"><%= link_to "Portfolio", portfolio_path %></li>
					<li class="<%= 'active' if current_page?(contacts_path) %>"><%= link_to "Contatti", contacts_path %></li>
				</ul>	
			</nav>
			<nav id="middle-nav">
				<ul class="nav-list ul-lefted">
					<li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
					<li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_path %></li>
					<li class="dropdown">
						<div class="dropbtn row">Servizi <span class="material-icons" id="dropIcon">arrow_drop_down</span></i></div>
						<ul class="dropdown-content ul-lefted invisible" id="myDropdown">
							<li class="<%= 'active' if current_page?(drone_path) %>"><%= link_to "Drone", drone_path %></li>
							<li class="<%= 'active' if current_page?(survey_path) %>"><%= link_to "Rilievi", survey_path %></li>
							<!--<li class="<%= 'active' if current_page?(archeologia_path) %> invisible"><%= link_to "Archeologia", archeologia_path %></li>-->
							<li class="<%= 'active' if current_page?(print_path) %>"><%= link_to "Stampa 3D", print_path %></li>
						</ul>
					</li>			
					<li class="<%= 'active' if current_page?(portfolio_path) %>"><%= link_to "Portfolio", portfolio_path %></li>
					<li class="<%= 'active' if current_page?(contacts_path) %>"><%= link_to "Contatti", contacts_path %></li>
				</ul>	
			</nav>
			<nav id="mobile-nav">
        <div id="mySidenav" class="sidenav">
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
          <%= link_to "Home", root_path %>
         	<%= link_to "About", about_path %>
					<%= link_to "Drone", drone_path %>
					<%= link_to "Rilievi", survey_path %>
					<%= link_to "Archeologia", archeologia_path,  style:"display: none;" %>
					<%= link_to "Stampa 3D", print_path %>
					<%= link_to "Portfolio", portfolio_path %>
					<%= link_to "Contatti", contacts_path %>
        </div>

        <!-- Use any element to open the sidenav -->
        <i onclick="openNav()"class="material-icons" id="menu" style="cursor: pointer;">menu</i>  
      </nav>
		</div>

	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="it">
  <head>
    <title>VerticalEye | <%= yield(:title) %></title>
    <meta name="description" content="<%= yield(:meta_desc) %>">
    <!--favicon START-->
    <link rel="apple-touch-icon" sizes="180x180" href="assets/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="assets/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="assets/favicon/favicon-16x16.png">
    <link rel="manifest" href="assets/favicon/site.webmanifest">
    <link rel="mask-icon" href="assets/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="assets/favicon/favicon.ico">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="assets/favicon/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
    <!--favicon FINE-->
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'grid-sistem', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', :defer => "defer" %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="https://fonts.googleapis.com/css2?family=Teko&display=swap" rel="stylesheet">
  	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script type="text/javascript" async>
      var _iub = _iub || [];
      _iub.csConfiguration = {"consentOnContinuedBrowsing":false,"perPurposeConsent":true,"enableCMP":true,"googleAdditionalConsentMode":true,"isTCFConsentGlobal":false,"whitelabel":false,"lang":"it","siteId":1958527,"cookiePolicyId":47765479, "banner":{ "acceptButtonDisplay":true,"customizeButtonDisplay":true,"acceptButtonColor":"#f4992c","acceptButtonCaptionColor":"#010101","customizeButtonColor":"#DADADA","customizeButtonCaptionColor":"#4D4D4D","position":"bottom","textColor":"#ffffff","backgroundColor":"#010101","rejectButtonColor":"#0073CE","rejectButtonCaptionColor":"white","brandBackgroundColor":"none","brandTextColor":"#ffffff" }};
    </script>
    <script type="text/javascript" src="//cdn.iubenda.com/cs/tcf/stub-v2.js" async></script>
    <script type="text/javascript" src="//cdn.iubenda.com/cs/iubenda_cs.js" charset="UTF-8" async></script>
  </head>

  <body>
    
    <%= render "layouts/header" %>
    <div class="container-fluid col-flex" id="initial">
      <div class="logo">
        <%= image_tag("biancovero trasparente_fermoepausa_loop.gif") %>
      </div>
    </div>
    <main id="main">
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
  <%= javascript_include_tag 'script', :defer => "defer" %>
</html>

app/views/pages/about.html.erb
<% provide(:title, "Professionisti qualificati al tuo servizio") %>
<% provide(:meta_desc, "Soluzioni con droni, su misura, per rilievi topografici, ispezioni e riprese in tempi ridotti, applicabili in svariati campi: Edilizia, Progettazione, Certificazione, Efficientamento, Restauro Archeologia, Promozione e pubblicità, Agricoltura, Allevamento") %>
<div class="hero container-fluid white-text center-text B s2 " id="hero-about">
	<div class="hero-titlebox">
	</div>
	<div class="title-container"><h1>CHI SIAMO</h1></div>
</div>
<section class="container-fluid col-flex white-text" id="mission">
	<div class="widescreen-post-hero">
		<h2 class="s4 animation-element fade-from-top center-text">Professionisti qualificati al tuo servizio</h2>
	</div>
	<div class="container-md col-flex">
		<div class="rounded s2">
			<p class="justified animation-element fade-from-left" ><strong>VERTICAL EYE</strong> è un progetto nato nel 2018 da un’idea di Andrea La Torre e Filippo Trogi.
			Laureati entrambi in Archeologia e culture del mondo antico, lavoriamo da diversi anni non solo nel settore archeologico, ma anche in quello topografico.
			Intuendo poi le potenzialità offerte dalle nuove tecnologie, come i sempre più avanzati software di rilievo fotogrammetrico, la nostra attenzione si è spostata sulla possibilità di approcciarci al rilievo in maniera più <strong>innovativa</strong>. Da qui all'idea di ottenere, grazie ai SAPR (droni), una gran quantità di riprese aeree a costi e tempistiche contenuti, il passo è stato breve. Si è così aperto un mondo di potenzialità: con questi mezzi le possibilità di ottimizzare e facilitare lavori già esistenti sono quasi infinite ed è così che piano piano ne abbiamo studiate e sperimentate diverse, fino ad arrivare a mettere a terra il progetto Vertical Eye e delineare accuratamente la gamma di servizi che offriamo.
			</p>
		</div>
	</div>
</section>
<section class="container-fluid" id="team">
	<div class="container">
		<h2 class="center-text s4 white-text animation-element fade-from-top loop">Il team di Vertical Eye</h2>
		<br>
		<div class="container center-text animation-element fade-from-left loop">
			<div class="row">
				<div class="col-sm-6 flip-card">
					<div class="flip-card-inner">
				    <div class="flip-card-front">
				      <div class="col-flex"><%= image_tag("Andre.png", alt: "Andrea La Torre") %></div>
			     		<h3 class="s3">Andrea La Torre</h3>
				    </div>
				    <div class="flip-card-back">
				      <h4 class="s2">Andrea La Torre</h4>
				      <ul class="s1 ul-lefted">
				      	<li><p>Dottore in Archeologia e Culture del Mondo antico</p></li>
				      	<li><p>Pilota di droni livello CRO</p></li>
				      	<li><p>Specializzato in riprese fotografiche e video</p></li>
				      	<li><p>Specializzato nell'uso di software di post-produzione foto/video e fotogrammetrici</p></li>
				      	<li><p></p></li>
				      </ul>
				    </div>
				  </div>
				</div>
				<div class="col-sm-6 flip-card">
					<div class="flip-card-inner">
				    <div class="flip-card-front">
				      <div class="col-flex">
				      	<%= image_tag("Fillo.png", alt: "Filippo Trogi") %>
				      </div>
				      <h3 class="s3">Filippo Trogi</h3>
				    </div>
				    <div class="flip-card-back">
				      <h4 class="s2">Filippo Trogi</h4>
				      <ul class="s1 ul-lefted">
				      	<li><p>Dottore in Archeologia e Culture del Mondo Antico</p></li>
				      	<li><p>Pilota di droni livello CRO</p></li>
				      	<li><p>Specializzato nel rilievo topografico</p></li>
				      	<li><p>Specializzato nell'uso di software fotogrammetrici, CAD e GIS</p></li>
				      	<li><p>Front-end web developer</p></li>
				      </ul>
				    </div>
				  </div>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="container-fluid fade-from-bottom animation-element" id="fleet">
	<div class="container-md s1 white-text card-border">
		<h2 class="center-text s4">La nostra flotta</h2>
		<div>
			<div class="container-sm" id="s900">
				<h3 class="center-text s3">DJI S900</h3>
				<div class="row">	
					<div class="col-sm-4 col-flex">
						<div class="img-round">
							<%= image_tag("s900.png", alt: "DJI S900") %>
						</div>
					</div>
					<div class="col-sm-8 row-top">
						<div class="col-sm-6">
							<ul>
								<h4 class="up s2">Caratteristiche principali</h4>
								<li><p>20 minuti di autonomia di volo</p></li>
								<li><p>Volo autonomo per missioni con waypoint GPS</p></li>
								<li><p>Posizionamento GPS</p></li>
								<li><p>Ritorno a casa automatico in caso emergenza</p></li>
								<li><p>Scatola nera con registrazione log di volo + dati GPS</p></li>
								<li><p>Gimbal brushless a 3 assi per riprese stabilizzate</p></li>
								<li><p>Fotocamera Panasonic Loomix GH4 con sensore Live-MOS da 16.5MP</p></li>
								<li><p>Obiettivo fisso da 35 mm</p></li>
								<li><p>Riprese video in risoluzione 4k</p></li>
								<li><p>Possibilità di installare altri tipi di payload, come termocamere, lidar o camere multispettrali</p></li>
							</ul>
						</div>
						<div class="col-sm-6">
							<ul>
								<h4 class="up s2">Campi di utilizzo</h4>
								<li><p>Aerofotogrammetria</p></li>
								<li><p>Topografia</p></li>
								<li><p>Rilievo digitale al di sotto della vegetazione</p></li>
								<li><p>DEM/ DSM/ DTM e curve di livello</p></li>
								<li><p>Ortofoto con risoluzione fino a 1cm/pixel</p></li>
								<li><p>Monitoraggio frane e cave</p></li>
								<li><p>Ispezioni termiche (fotovoltaico)</p></li>
								<li><p>agricoltura di precisione</p></li>
								<li><p>ispezioni video/fotografiche</p></li>
								<li><p>fotografie e riprese aeree</p></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<br>
			<div class="container-sm" id="Q500">
				<h3 class="center-text s3">Yuneek Typhoon Q500 4K</h3>
				<div class="inverted">
					<div class="col-sm-4 col-flex">
						<div class="img-round">
							<%= image_tag("Typhoon.png", alt: "Thyphoon Q500 4k") %>
						</div>
					</div>
					<div class="col-sm-8 row-top">
						<div class="col-sm-6">
							<ul>
								<h4 class="up s2">Caratteristiche principali</h4>
								<li><p>15 minuti di autonomia di volo</p></li>
								<li><p>Posizionamento GPS</p></li>
								<li><p>Ritorno a casa automatico in caso emergenza</p></li>
								<li><p>Scatola nera con registrazione log di volo + dati GPS</p></li>
								<li><p>Gimbal brushless a 3 assi per riprese stabilizzate</p></li>
								<li><p>Fotocamera con sensore CMOS 1/2.3" da 12MP</p></li>
								<li><p>Obiettivo fisso da 14 mm F2.8 con correzione della distorsione</p></li>
								<li><p>Riprese video in risoluzione 4k</p></li>
							</ul>
						</div>
						<div class="col-sm-6">
							<ul class="caps">
								<h4 class="up s2">Campi di utilizzo</h4>
								<li><p>Aerofotogrammetria</p></li>
								<li><p>Topografia</p></li>
								<li><p>DEM/ DSM/ DTM e curve di livello</p></li>
								<li><p>Ortofoto con risoluzione fino a 5cm/pixel</p></li>
								<li><p>rilievi architettonici</p></li>
								<li><p>ispezioni video/fotografiche</p></li>
								<li><p>fotografie e riprese aeree</p></li>
							</ul>
						</div>
					</div>
					
				</div>
			</div>
			<br>
			<div class="container-sm" id="Spark">
				<h3 class="center-text s3">DJI Spark</h3>
				<div class="row">
					<div class="col-sm-4 col-flex">
						<div class="img-round">
							<%= image_tag("Spark.png", alt: "DJI Spark") %>
						</div>
					</div>
					<div class="col-sm-8 row-top">
						<div class="col-sm-6">
							<ul>
								<h4 class="up s2">Caratteristiche principali</h4>
								<li><p>15 minuti di autonomia di volo</p></li>
								<li><p>Posizionamento GPS e sensori anti-collisione</p></li>
								<li><p>Ritorno a casa automatico in caso emergenza</p></li>
								<li><p>Gimbal brushless a 2 assi per riprese stabilizzate</p></li>
								<li><p>Fotocamera con sensore CMOS 1/2.3" da 12MP</p></li>
								<li><p>Obiettivo fisso da 25 mm F2.8 c</p></li>
								<li><p>Riprese video in risoluzione FHD</p></li>
							</ul>
						</div>
						<div class="col-sm-6">
							<ul>
								<h4 class="up s2">Campi di utilizzo</h4>
								<li><p>Aerofotogrammetria</p></li>
								<li><p>DEM/ DSM/ DTM e curve di livello</p></li>
								<li><p>Ortofoto con risoluzione fino a 5cm/pixel</p></li>
								<li><p>rilievi architettonici</p></li>
								<li><p>ispezioni video/fotografiche</p></li>
								<li><p>fotografie e riprese aeree</p></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<br>
<section class="container-fluid animation-element fade-in" id="tools">
	<div class="container-md card-border s1">
		<h2 class="center-text s4">La nostra attrezzatura per il rilievo</h2>
		<div>
			<div class="container-sm" id="Stonex">
				<h3 class="center-text s3">Antenna GNSS differenziale Stonex S8 Plus</h3>
				<div class="row">	
					<div class="col-sm-6 col-flex">
						<div class="img-round">
							<%= image_tag("stonex.png", alt: "Stonex S8") %>
						</div>
					</div>
					<div class="col-sm-6">
						<ul>
							<h4 class="up s2">Caratteristiche principali</h4>
							<li><p>120 canali</p></li>
							<li><p>4 costellazioni</p></li>
							<li><p>Radiomodem UHF</p></li>
							<li><p>Modem 3G WCDMA per correzione differenziale</p></li>
							<li><p>Bluetooth</p></li>
							<li><p>Palmare con programma GIS integrato</p></li>
							<li><p>Certificazione IP67</p></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="container-sm" id="Ruide">
				<h3 class="center-text s3">Stazione Totale Ruide R820</h3>
				<div class="inverted">
					<div class="col-sm-6 col-flex">
						<div class="img-round">
							<%= image_tag("ruide.png", alt: "Ruide") %>
						</div>
					</div>
					<div class="col-sm-6">
						<ul>
							<h4 class="up s2">Caratteristiche principali</h4>
							<li><p>600m|5000m / distanza massima in modalità non-prism|single prism</p></li>
							<li><p>2mm+2ppm / precisione (modalità prisma)</p></li>
							<li><p>0.3s / tempo di misurazione</p></li>
							<li><p>2" / precisione angolare</p></li>
							<li><p>4' / range di compensazione</p></li>
							<li><p>Sensore automatico di temperatura e pressione</p></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/pages/home.html.erb
<% provide(:title, "Soluzioni con drone") %>
<% provide(:meta_desc, "Soluzioni con droni, su misura, per rilievi topografici, ispezioni e riprese in tempi ridotti, applicabili in svariati campi: Edilizia, Progettazione, Certificazione, Efficientamento, Restauro Archeologia, Promozione e pubblicità, Agricoltura, Allevamento") %>
<div class="hero container-fluid white-text center-text B" id="hero-home">
	<div class="hero-titlebox"></div>
	<div class="title-container"><h1>VERTICAL EYE <br> Drone Solutions</h1></div>
</div>
<br>
<section class="container-fluid col-flex white-text" id="value-proposition">
	<div class="widescreen-post-hero">
		<h2 class="s4 center-text animation-element fade-from-top">Un altro punto di vista è possibile</h2>
	</div>
	<div class="container-md center-text">
		<div class="rounded s2">
			<p class="justified animation-element fade-from-left">L'uomo ha sempre bramato di volare, di poter osservare e immortalare il mondo da un'altra prospettiva: dagli esperimenti di Leonardo ai primi palloni aerostatici fino ai più modermi aerei.<br>Oggi, grazie ai droni, è possibile farlo in modo sempre più accessibile ed economico!</p>
		</div>
	</div>
</section>
<section class="col-flex justified container-fluid widescreen white-text" id="brand-identity">
	<div class="col-flex container-fluid" id="campi">
		<div class="container-md">
			<p class="s2 animation-element fade-from-top">La <strong>MISSION di VERTICAL EYE</strong> è quella di mettere al servizio di aziende e privati <strong>personale qulificato e sempre aggiornato in materia di tecnologie e normative</strong>, avvalendosi anche di collaborazioni esterne, al fine di garantire sempre operazioni di qualità, sviluppate e realizzate attorno alle esigenze del cliente.
			<br><br>
			Pertanto offriamo un gamma di servizi (con Drone e non solo), che permettono di osservare, registrare e misurare la realtà da un nuovo punto di vista, raggiungendo spazi inediti e aree altrimenti inaccessibili, in tempi contenuti, fornendo servizi preziosi nei campi di:</p>
		</div>
		<div class=" animation-element  fade-in">
				<%= image_tag("Icone.png", alt:"campi d'applicazione", title:"Campi d'applicazione")%>
		</div>
	</div>
</section>
<section class="col-flex widescreen white-text" id="elements">				
	<div class="col-flex container s1">
		<div class="elements-container" id="icondwn">	
			<div class="el-item lower">
				<i class="material-icons">camera</i>
				<br>
				<div class="caption">
					<%= link_to "RIPRESE AEREE", drone_path %>
				</div>				
			</div>
			<div class="el-item upper">
				<i class="material-icons">map</i>
				<br>
				<div class="caption">
					<%= link_to "RILIEVI", survey_path %>
				</div>
			</div>
			<div class="el-item lower">
				<i class="material-icons">search</i>
				<br>
				<div class="caption">
					<%= link_to "ISPEZIONI", drone_path %>
				</div>
			</div>
		</div>
		<div class="elements-container" id="logo-hover">
			<div class="el-item animation-element fade-in loop" id="el-logo">

			</div>
		</div>
		<div class="elements-container" id="iconup">	
			<div class="el-item upper">
				<i class="material-icons">settings</i>
				<br>
				<div class="caption">
					<%= link_to "INNOVAZIONE", print_path %>
				</div>
			</div>
			<div class="el-item lower">
				<i class="material-icons">group</i>
				<br>
				<div class="caption"><%= link_to "Personale qualificato", about_path %></div>		
			</div>
			<div class="el-item upper">
				<i class="material-icons">flash_on</i>
				<br>
				<div class="caption">
					<p>Tempi rapidi</p>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="bg-4 col-flex half-screen-sm" id="cta-1">
	<div class="container animation-element fade-from-bottom">
		<h2 class="up center-text white-text s3">scopri i nostri servizi</h2>
		<br>
		<div class="row s2">
			<div class="col-md-3 col-flex">
				<%= link_to "RILIEVI", survey_path, class:"btn white-text o-bg" %>
			</div>
			<div class="col-md-3 col-flex">
				<%= link_to "DRONI", drone_path, class:"btn white-text o-bg" %>
			</div>
			<div class="col-md-3 col-flex">
				<%= link_to "ARCHEOLOGIA", archeologia_path, class:"btn white-text o-bg" %>
			</div>
			<div class="col-md-3 col-flex">
				<%= link_to "STAMPA 3D", print_path, class:"btn white-text o-bg" %>
			</div>
		</div>
	</div>
</section>
<section class=" half-screen-sm col-flex white-text" id="partners">
	<div class="container-md s3">
		<h2 class="up center-text">le nostre collaborazioni</h2>
		<div class="row">
			<div class="col-md-6 center-text">
				<div class="logo-coll">
					<a href="https://www.binarioprint.it" target="_blank">
						<%= image_tag("binarioprint.png", alt:"binarioprint stampa 3D", title:"Binarioprint", class:"images-xs") %>
					</a> 
				</div>
			</div>
			<div class="col-md-6 center-text">
				<div class="logo-coll">
					<a href="https://www.godian.it" target="_blank">
						<%= image_tag("Godian.png", alt:"godian videomaker", title:"Godian", class:"images-xs") %>
					</a> 
				</div>

			</div>
		</div>
	</div>
</section>